using Hpmv;
using UnityEngine;
using Team17.Online.Multiplayer.Messaging;
using SuperchargedPatch;
using SuperchargedPatch.Bridge;
using SuperchargedPatch.Authoring.Modules;
using Mono.Cecil;
int checks=0;
void Check(bool value,string why){if(!value)throw new Exception(why);checks++;}
void Reject(Action run,string why){try{run();}catch(ArgumentException){checks++;return;}catch(InvalidOperationException){checks++;return;}throw new Exception("Missing rejection: "+why);}
Dictionary<string,object> Args()=>new(){{"entityId",51L}};
var raw=new GameObject{name="SushiFish"};raw.transform.position=new(){x=8.4f,y=.5f,z=-7.2f};
var entry=new Entry{m_Header=new(){m_uEntityID=51},m_GameObject=raw,m_ServerSynchronisedComponents=new(){_items=new[]{new Sync{Type=1},new Sync{Type=11},new Sync{Type=17}}}};
EntitySerialisationRegistry.m_EntitiesList._items=new[]{entry};
var existing=new EntityRegistryData{EntityId=1,Name="original"};
Injector.Server.CurrentFrameData.EntityRegistry=new(){existing};
var module=new RegistryObserverModule();var frame=Injector.Server.CurrentFrameData;
var bodyBefore=NativeSceneMetadata.InitialRigidBodyIds.ToArray();var attachBefore=NativeSceneMetadata.InitialPhysicalAttachmentIds.ToArray();
var absent=(Dictionary<string,object>)module.Invoke("refresh",Args());
Check((int)absent["published"]==1&&frame.EntityRegistry.Count==2&&ReferenceEquals(frame.EntityRegistry[0],existing),"Single selected observation appended preserving prior queued receipt");
Check(frame.EntityRegistry[1].SpawnNames==null,"Absent collection is not invented as empty");
Check(frame.EntityRegistry[1].EntityId==51&&frame.EntityRegistry[1].Name=="SushiFish"&&frame.EntityRegistry[1].Pos.X==raw.transform.position.x,"Actual selected identity/name/pose copied");
Check(frame.EntityRegistry[1].SyncEntityTypes.SequenceEqual(new[]{1,11,17}),"Native component codec order preserved");
var collection=new SpawnableEntityCollection();collection.spawnables.Add(new(){name="ChoppedSushiFish"});collection.spawnables.Add(new(){name="second-native-child"});raw.components.Add(collection);
module.Invoke("refresh",Args());var published=frame.EntityRegistry[^1];
Check(published.SpawnNames.SequenceEqual(new[]{"ChoppedSushiFish","second-native-child"}),"Late native ordered spawn metadata observed");
collection.spawnables[0].name="changed-later";Check(published.SpawnNames[0]=="ChoppedSushiFish","Published observation is a value snapshot");
Check(bodyBefore.SequenceEqual(NativeSceneMetadata.InitialRigidBodyIds)&&attachBefore.SequenceEqual(NativeSceneMetadata.InitialPhysicalAttachmentIds),"Initial fixed sets preserved");
Check(ReferenceEquals(frame,Injector.Server.CurrentFrameData)&&frame.FrameNumber==180,"No frame commit or invented native advance");
int count=frame.EntityRegistry.Count;
Reject(()=>module.Invoke("refresh",new()),"missing selector");Reject(()=>module.Invoke("refresh",new(){{"entityId",51.0}}),"floating selector");
Reject(()=>module.Invoke("refresh",new(){{"entityId",0L}}),"zero selector");Reject(()=>module.Invoke("refresh",new(){{"entityId",52L}}),"missing native entity");
TimeManager.Paused=false;Reject(()=>module.Invoke("refresh",Args()),"running");TimeManager.Paused=true;
NativeSessionBridge.InputBlocked=false;Reject(()=>module.Invoke("refresh",Args()),"unfenced");NativeSessionBridge.InputBlocked=true;
EntitySerialisationRegistry.m_EntitiesList._items=new[]{entry,entry};Reject(()=>module.Invoke("refresh",Args()),"ambiguous ID");EntitySerialisationRegistry.m_EntitiesList._items=new[]{entry};
raw.transform.position=new(){x=float.NaN};Reject(()=>module.Invoke("refresh",Args()),"invalid pose");raw.transform.position=new(){x=1};
raw.OnRead=()=>entry.m_GameObject=new(){name="successor"};Reject(()=>module.Invoke("refresh",Args()),"incarnation changed during read");raw.OnRead=null;entry.m_GameObject=raw;
Check(frame.EntityRegistry.Count==count,"Rejected reads publish no partial observations");
raw.OnRead=()=>NativeSceneMetadata.InitialPhysicalAttachmentIds.Add(999);Reject(()=>module.Invoke("refresh",Args()),"initial set changed during read");raw.OnRead=null;NativeSceneMetadata.InitialPhysicalAttachmentIds.Remove(999);
Check(frame.EntityRegistry.Count==count,"Initial-set rejection preserves queued observations");
module.Dispose();Reject(()=>module.Invoke("refresh",Args()),"disposed");
var absentModule=new RegistryObserverModule();
Dictionary<string,object> Absent()=>new(){{"entityId",52L},{"sceneMetadataRefreshes",3L},{"priorBodyInstanceId",-999L}};
var gone=(Dictionary<string,object>)absentModule.Invoke("observe-absent",Absent());
Check((bool)gone["ok"] && !(bool)gone["historicalRemovalEventObserved"] && (string)gone["source"]=="observed-native-registry-absence","Current absence receipt does not claim a historical callback");
Check(frame.ServerMessages.SequenceEqual(new uint[]{52})&&frame.FrameNumber==180&&ReferenceEquals(EntitySerialisationRegistry.m_EntitiesList._items[0],entry),"Only framework retirement observation emitted; native registry/frame unchanged");
var badEpoch=Absent();badEpoch["sceneMetadataRefreshes"]=2L;Reject(()=>absentModule.Invoke("observe-absent",badEpoch),"stale native scene");
var fixedId=Absent();fixedId["entityId"]=49L;Reject(()=>absentModule.Invoke("observe-absent",fixedId),"initial fixed object");
var present=Absent();present["entityId"]=51L;Reject(()=>absentModule.Invoke("observe-absent",present),"currently present entity");
var zero=Absent();zero["priorBodyInstanceId"]=0L;Reject(()=>absentModule.Invoke("observe-absent",zero),"absent prior body identity");
var aliveBody=new Rigidbody();raw.components.Add(aliveBody);var aliased=Absent();aliased["priorBodyInstanceId"]=(long)aliveBody.GetInstanceID();Reject(()=>absentModule.Invoke("observe-absent",aliased),"prior body still registered under another ID");
NativeSessionBridge.InputBlocked=false;Reject(()=>absentModule.Invoke("observe-absent",Absent()),"unfenced absence");NativeSessionBridge.InputBlocked=true;
TimeManager.Paused=false;Reject(()=>absentModule.Invoke("observe-absent",Absent()),"running absence");TimeManager.Paused=true;
Check(frame.ServerMessages.Count==1 && bodyBefore.SequenceEqual(NativeSceneMetadata.InitialRigidBodyIds)&&attachBefore.SequenceEqual(NativeSceneMetadata.InitialPhysicalAttachmentIds),"All rejected reconciliations leave queues and initial memberships untouched");
using var dll=AssemblyDefinition.ReadAssembly(args[0]);
var type=dll.MainModule.GetType("SuperchargedPatch.Authoring.Modules.RegistryObserverModule");
var calls=type.Methods.Where(m=>m.HasBody).SelectMany(m=>m.Body.Instructions).Select(i=>i.Operand).OfType<MethodReference>().Select(m=>m.FullName).ToArray();
Check(calls.Count(m=>m.Contains("Hpmv.OutputData::set_EntityRegistry"))==1,"Compiled native module has one observer queue publication site");
Check(!calls.Any(m=>m.Contains("NativeSceneMetadata::Refresh")||m.Contains("CommitFrame")||m.Contains("RequestFullObservation")||m.Contains("UnityEngine.Transform::set_")||m.Contains("UnityEngine.Rigidbody::set_")),"Compiled module has no broad refresh, frame commit, cache reset or native physics setters");
Check(calls.Any(m=>m.Contains("SpawnableEntityCollectionExt::GetSpawnables")),"Compiled code uses existing native ordered spawn-list reader");
Check(calls.Count(m=>m.Contains("EntityRetirementMessageSender::SendMessageToRetireEntity(System.UInt32)"))==1,"Compiled observer uses one existing framework-only retirement publication site");
Console.WriteLine(System.Text.Json.JsonSerializer.Serialize(new{ok=true,checks,gameCalls=0,module=args[0],scope="Focused observation/guard fixtures plus compiled frozen-X module call audit; native delivery is measured separately."}));
